backend:
  name: github
  repo: arya1106/team1991-grommet
  base_url: https://team1991-grommet.vercel.app/
  auth_endpoint: api/auth
media_folder: public/img #images that are uploaded via Netlify Cms interface will be stored in this folder
public_folder: img #I dont know
collections:
  - name: "newsfeed" # Used in routes, e.g., /admin/collections/blog
    label: "News Feed Post" # Used in the UI
    folder: "posts"
    create: true # Allow users to create new markdown files.
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for front matter. You will need to modify fields according to your project.
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publishing Date", widget: "datetime", name: "date", format: "X", date_format: true, time_format: true}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Featured Image", required: false, name: "thumbnail", widget: "image"}
      - {label: "Author", name: "author", widget: "string", default: "Admin"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "robots"
    label: "Robot"
    folder: "robots"
    create: true
    slug: "{{slug}}"
    identifier_field: "gameName"
    fields:
      - {label: "Game Name", name: "gameName", widget: "string"}
      - {label: "Season Year", name: "seasonYear", widget: "string"}
      - {label: "Robot Image", name: "robotImage", widget: "image"}
      - {label: "Robot/Game Description", name: "robotBlurb", widget: "markdown"} 
  - name: "awards"
    label: "Award"
    folder: "awards"
    create: true
    slug: "{{slug}}"
    identifier_field: "awardFilename"
    fields:
      - {label: "Award File Name", name: "awardFilename", widget: "string", hint: "A unique identifier for the file this data will be stored in."}
      - {label: "Award Name", name: "awardName", widget: "string"}
      - {label: "Year", name: "awardYear", widget: "string"}
      - {label: "Event", name: "awardEvent", widget: "string", hint: "Follows the format \"NE District - Hartford Event\" or \"Off-season event - WPI Battlecry\""}
      - {label: "Description", name: "awardDescription", widget: "string"}
